export const addNewPLaylistData = [
  {
    labelText: 'Title',
    inputType: 'text',
    id: 'title',
    message: 'Need to be filled out',
    required: true,
    minLength: 1,
  },
  {
    labelText: 'Creator',
    inputType: 'text',
    id: 'creator',
    message: 'Need to be filled out',
    required: true,
    minLength: 1,
  },
  {
    labelText: 'Playlist link',
    inputType: 'text',
    id: 'playlistLink',
    message: 'Need to be filled out',
    required: true,
    minLength: 1,
  },
  {
    labelText: 'Playlist iframe',
    inputType: 'text',
    id: 'playlistIframe',
    message: 'Need to be filled out',
    required: true,
    minLength: 1,
  },
  {
    labelText: 'Order',
    inputType: 'number',
    id: 'order',
    message: 'Need to be filled out',
    required: true,
  },
];
